// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lov-cinematic/Cinematic.tsx": () => import("../components/mockups/lov-cinematic/Cinematic.tsx"),
  "./components/mockups/lov-gothic/Gothic.tsx": () => import("../components/mockups/lov-gothic/Gothic.tsx"),
  "./components/mockups/lov-gritty/Gritty.tsx": () => import("../components/mockups/lov-gritty/Gritty.tsx")
};
